sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dev/docker-react npm run test

deploy:
       provider: elasticbeanstalk
       region: "us-east-1"
       app: "docker-react"
       env: "Dockerreact-env"
       bucket_name: "elasticbeanstalk-us-east-1-643027122881"
       bucket_path: "docker-react"
on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_aceess_key: "$AWS_SECRET_KEY"
        
