sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dev/docker-react npm run test

deploy:
       skip_cleanup: true
       provider: elasticbeanstalk
       region: "us-east-1"
       app: "docker-react"
       env: "Dockerreact-env"
       bucket_name: "elasticbeanstalk-us-east-1-643027122881"
       bucket_path: "docker-react"
       edge: true
       access_key_id: AKIAZLN3HHLAWHXQDXLS
       secret_aceess_key: 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
      on:
         branch: master
            
